apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: nettool
  name: nettool
spec:
  containers:
  - command:
    - sleep
    - "6000000000000"
    image: registry.localdomain:5000/wbitt/network-multitool
    name: nettool
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: private-registry
  restartPolicy: Always
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: harvester-whereabouts