packages:
  - bash-completion
  - bpftool
  - conntrack
  - container-selinux
  - git
  - info
  - jq
  - kernel-modules-extra
  - man-pages
  - nmap
  - socat
  - unzip
  - vim
package_update: true
package_upgrade: true
write_files:
  - content: |
      [keyfile]
      unmanaged-devices=interface-name:cilium*;interface-name:lxc*
    path: /etc/NetworkManager/conf.d/rke2-cilium.conf
  - content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
    path: /etc/sysctl.d/99-ip-forwarding.conf
  - content: |
      br_netfilter
      overlay
    path: /etc/modules.load.d/10-rke2-modules.conf
  - content: |
      Defaults secure_path="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/var/lib/rancher/rke2/bin"
    path: /etc/sudoers.d/40-secure-path
  - content: |
      kernel.panic              = 10
      kernel.panic_on_oops      = 1
      vm.overcommit_memory      = 1
      vm.panic_on_oom           = 0
    path: /etc/sysctl.d/60-rke2-cis.conf