#cloud-config
package_update: false
runcmd:
  - - systemctl
    - enable
    - '--now'
    - qemu-guest-agent
ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGUV5mYJt2mNSayglG9+ez4W66Cj5PdBfvg5+Mqf+e9G