---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: sles16-disk-0
  namespace: homelab-demo
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
  storageClassName: longhorn-opensuse-leap-15-6
  volumeMode: Block
---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: sles16-cloudinit
  namespace: homelab-demo
data:
  networkdata: ""
  userdata: I2Nsb3VkLWNvbmZpZwpwYWNrYWdlX3VwZGF0ZTogZmFsc2UKcnVuX2NtZDoKICAtIC0gc3lzdGVtY3RsCiAgICAtIGVuYWJsZQogICAgLSAtLW5vdwogICAgLSBxZW11LWd1ZXN0LWFnZW50CnNzaF9hdXRob3JpemVkX2tleXM6CiAgLSBzc2gtZWQyNTUxOSBBQUFBQzNOemFDMWxaREkxTlRFNUFBQUFJR1VWNW1ZSnQybU5TYXlnbEc5K2V6NFc2NkNqNVBkQmZ2ZzUrTXFmK2U5Rwo=
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  creationTimestamp: null
  name: sles16
  namespace: homelab-demo
spec:
  runStrategy: RerunOnFailure
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: network.harvesterhci.io/vmnet
                operator: In
                values:
                - "true"
      architecture: amd64
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: disk-0
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - bridge: {}
            model: virtio
            name: default
        memory:
          guest: 4Gi
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: 125m
            memory: 2730Mi
      hostname: sles16
      networks:
      - multus:
          networkName: harvester-public/vmnet1
        name: default
      volumes:
      - name: disk-0
        persistentVolumeClaim:
          claimName: sles16-disk-0
      - cloudInitNoCloud:
          networkDataSecretRef:
            name: sles16-cloudinit
          secretRef:
            name: sles16-cloudinit
        name: cloudinitdisk