---
kube-apiserver-arg:
- tls-min-version=VersionTLS13
- audit-log-path=/var/lib/rancher/rke2/server/logs/audit.log
- anonymous-auth=false
- authorization-mode=RBAC,Node
- audit-log-maxage=30
- audit-log-mode=blocking-strict
- audit-policy=/etc/rancher/rke2/audit-policy.yaml
kube-controller-manager-arg:
- bind-address=127.0.0.1
- tls-min-version=VersionTLS13
- use-service-account-credentials=true
kube-scheduler-arg:
- tls-min-version=VersionTLS13
kubelet-arg:
- anonymous-auth=false
- read-only-port=0
- authorization-mode=Webhook
- streaming-connection-idle-timeout=5m
- protect-kernel-defaults=true
pod-security-admission-config-file: /etc/rancher/rke2/rke2-pss.yaml
profile: cis
secrets-encryption: true
selinux: true
write-kubeconfig-mode: "0640"