---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    bpf:
      distributedLRU:
        enabled: true
      mapDynamicSizeRatio: 0.08
      masquerade: true
      preallocateMaps: true
    bpfClockProbe: true
    gatewayAPI:
      enabled: true
    routingMode: tunnel
    kubeProxyReplacement: true
    k8sServiceHost: localhost
    k8sServicePort: "6443"