apiVersion: harvesterhci.io/v1beta1
kind: VirtualMachineImage
metadata:
  creationTimestamp: null
  name: rocky-9
  namespace: harvester-public
spec:
  backend: backingimage
  displayName: Rocky-9-GenericCloud-Base.latest.x86_64.qcow2
  sourceType: download
  targetStorageClassName: rocky-9-image
  url: http://192.168.3.138:8080/Rocky-9-GenericCloud-Base.latest.x86_64.qcow2