apiVersion: harvesterhci.io/v1beta1
kind: VirtualMachineImage
metadata:
  creationTimestamp: null
  name: sles-16-0
  namespace: harvester-public
spec:
  backend: backingimage
  displayName: SLES-16.0-Minimal-VM.x86_64-Cloud-QU1.qcow2
  sourceType: download
  targetStorageClassName: sles-16-0-image
  url: http://192.168.3.138:8080/SLES-16.0-Minimal-VM.x86_64-Cloud-QU1.qcow2