#cloud-config
ca_certs:
  trusted:
  - |
    -----BEGIN CERTIFICATE-----
    MIIFsjCCA5qgAwIBAgIUTg64b924J4ibadrgKt5IsrW4738wDQYJKoZIhvcNAQEN
    BQAwcTEMMAoGA1UEBhMDVVNBMQswCQYDVQQIEwJUWDEPMA0GA1UEBxMGRGFsbGFz
    MRQwEgYDVQQKEwtBY29zdGEgSG9tZTEUMBIGA1UECxMLSW50ZXJuYWwgQ0ExFzAV
    BgNVBAMTDmFjb3N0YS1ob21lLWNhMB4XDTI1MTAxMDIzMzYwMFoXDTMwMTAwOTIz
    MzYwMFowcTEMMAoGA1UEBhMDVVNBMQswCQYDVQQIEwJUWDEPMA0GA1UEBxMGRGFs
    bGFzMRQwEgYDVQQKEwtBY29zdGEgSG9tZTEUMBIGA1UECxMLSW50ZXJuYWwgQ0Ex
    FzAVBgNVBAMTDmFjb3N0YS1ob21lLWNhMIICIjANBgkqhkiG9w0BAQEFAAOCAg8A
    MIICCgKCAgEAuWFEFIPI5lwpPHEsxD81W02nr6MTF0mL86cM4tdtlzFaqiJ69pu9
    d523MDutogtyWQSJNYfgZM/1OYwnkcDazw8UbTUG4drtejcaobonrD4VtOWzORsJ
    plNWrn7GRRKh2M1gWTqPDq0uRCZzs/x32gi1NTAiq9S/QpwQER8B+XwhDLbsxaa9
    p1p/s/QGpsXA8hZBzJ8KJ6IE79Z+LBtEd7xTVkyn/lO6RWT/ZoLjzU4UUiOX6ccn
    D/48eJz4kxtLLj7O0oQLTTE5ZnLJAO2OKk1zhFwfBP+qntrvkXR/+kz95Pa5UcR2
    KrgGCYylxszbqVNjQEWSkfaVbfhR3mokqy6/EHqhpXJvntLTp+S3zVnCNvEm7NSj
    xrLzDqwzBmObKrkvpa8TWITogUg5SqTAqZ4JrNRjszotkGbswfcknCgvLKF7ObyC
    fVNfOkL0C99VKzw6fLYq9qeDRC/VwvobgwzmspoBEMqRUa/IYz7vm5WwZmCnD7u6
    Boa6iTNstGlXXuDe386tt0EdJ4BjTEB9VTQezvrDXN0NyOkaSLXStwOTEgSNcRgr
    FZp0MJMpMr9r3tpp3HBnt2lNBxzfBER4Q9tm0Ziu4omUsQeHcdHkxIQuweet5DYv
    nSx96DIKyDkjge5oZQrslyt26FbTBZorHNtXh+Iiy7SSKDRpyfSRDkECAwEAAaNC
    MEAwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFAZZ
    v/IkOfyKYxv18t0PGYdzt/8tMA0GCSqGSIb3DQEBDQUAA4ICAQCzcXFJtFjG1DT1
    7lbAmnMc9sWzpr/qg08ZN2ugNBSGnsb7bbFBh96VF6RG3iVAstyuqzErgQHzu+5E
    PGjKux8+kf9/8H73Y3eXzWmNbZyGR1wF3jqGV6TpFkndHLlPXOFvLrfrLjbceiQh
    ZCQZjqLDG6xmrNYVKKD/vVL6U694tupys70oMwxidYsH4xcnxJcIHj4PD4sZ7WCf
    BOJiJOp0hcZKlv/dgup6Mueyn0Rw/Mn2GcmpKhxyrLRVGQXhvYXEq73zJ8uv9Cde
    1vzzDMXxU/ZaSdeagf2SUiwG3erVLRhV8rS/rU1F5Iv5MowwZvcf8rm7RmlLUzV/
    F6a/0lxmTqfEf4l7S0zI7AICFyLN1ZnYa+ITRnud9c3dG9D/XtU5dycmB3QWw44N
    HMyVhwWSYON4EMf25CK474gnI0+oQc4O5u8q9Tk1h+MpohN7xVOZDrCa09ch1ZvE
    KBa+9bAVRL/HNoTYhD4wA7TDeB40AbRkY2qi1g55x9hi0Dezk92q1Zfaeo6xeSAU
    bjOJ7puPsLQLMdwfM4iWW7riuHZf0g2pPIjSWaXUz3poB/r79zqH69+Aj/F7VjSh
    qumBsfCuFTGWKBCxDLO29rDv2DbzLQil6JNa7r5Bw8ilod4gAZDqquVwFP1gA9E9
    IiEqY9KvStTzZvlabQN+HpEgozdVFQ==
    -----END CERTIFICATE-----
packages:
  - bash-completion
  - qemu-guest-agent
package_update: true
runcmd:
  - - systemctl
    - enable
    - '--now'
    - qemu-guest-agent
ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGUV5mYJt2mNSayglG9+ez4W66Cj5PdBfvg5+Mqf+e9G
users:
  - default
  - name: etcd
    gecos: "etcd user"
    shell: /sbin/nologin
    system: true